# Generated by Django 4.2 on 2023-06-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
